#!/bin/bash

code --install-extension smlombardi.slime
code --install-extension vscode-icons-team.vscode-icons
code --install-extension mortim.noc-lang
code --install-extension ms-python.python
code --install-extension justusadam.language-haskell
code --install-extension redhat.java
code --install-extension ms-vscode.cpptools
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension yzhang.markdown-all-in-one
code --install-extension icrawl.discord-vscode
